image: "node:latest"

before_script:
    - yarn global add @graphprotocol/graph-cli

stages:
    - build
    - deploy

cache:
    paths:
        - node_modules/

install_dependencies:
    stage: build
    script:
        - yarn install
    artifacts:
        paths:
        - node_modules/

codegen:
    stage: build
    script:
        - yarn codegen

build:
    stage: build
    script:
        - yarn build

deploy:
    stage: deploy
    script:
        - graph deploy --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ $SUBGRAPH_NAME --access-token $GRAPH_ACCESS_TOKEN