image: "node:latest"

before_script:
    - apt-get update -qq && apt-get install -y libsecret-1-dev
    - yarn global add keytar
    - yarn global add @graphprotocol/graph-cli
    - graph auth https://api.thegraph.com/deploy/ --access-token $GRAPH_ACCESS_TOKEN 

stages:
    - build
    - deploy

cache:
    paths:
        - node_modules/

install_dependencies:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
        - node_modules/

codegen:
    stage: build
    script:
        - yarn codegen

build:
    stage: build
    script:
        - yarn build

deploy:
    stage: deploy
    script:
        - yarn deploy-staging